### PR TITLE
Add Conan as experimental package manager

### PR DESCRIPTION
**Pull request by riuzzoda**

### CODE REVIEW

**Review by canepat — CHANGES_REQUESTED** [review]
I also suggest to add some information in README file to describe how to use Conan package manager

**Comment by battlmonstr** [comment]
@dario1995 thanks for this contribution, good stuff  :+1:
I'm testing this now.

First, I've rebased this to the branch that uses Boost 1.81 (will be merged soon to master), and squashed all your commits for simplicity.

I have tested this and ran into issues:

1. Without `-DCONAN_PROFILE` autodetection fails:

```
-- CONAN_PROFILE not defined. Use autodetect settings...
CMake Error at build/conan.cmake:119 (message):
  Conan: Neither C or C++ was detected as a language for the project.
  Unabled to detect compiler version.
```

Most of our developers use Apple ARM computers with the latest macOS (currently 13 Ventura) and Xcode, currently 14 having this clang:

```
% clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.2.0
```

So it would be nice to either fix autodetection, or make macos_arm_clang_14_debug the default on macOS.

2. I'm getting errors during linking regarding absl and protobuf libraries:

```
Undefined symbols for architecture arm64:
  "absl::lts_20211102::FormatTime(std::__1::basic_string_view<char, std::__1::char_traits<char> >, absl::lts_20211102::Time, absl::lts_20211102::TimeZone)", referenced from:
      silkworm::log::BufferBase::BufferBase(silkworm::log::Level) in libsilkworm_noded.a(log.cpp.o)
  "absl::lts_20211102::strings_internal::CatPieces(std::initializer_list<std::__1::basic_string_view<char, std::__1::char_traits<char> > >)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > absl::lts_20211102::StrCat<>(absl::lts_20211102::AlphaNum const&, absl::lts_20211102::AlphaNum const&, absl::lts_20211102::AlphaNum const&, absl::lts_20211102::AlphaNum const&, absl::lts_20211102::AlphaNum const&) in libsilkworm_noded.a(tables.cpp.o)
  "absl::lts_20211102::ByString::ByString(std::__1::basic_string_view<char, std::__1::char_traits<char> >)", referenced from:
      absl::lts_20211102::strings_internal::Splitter<absl::lts_20211102::strings_internal::SelectDelimiter<char const*>::type, absl::lts_20211102::AllowEmpty, std::__1::basic_string_view<char, std::__1::char_traits<char> > > absl::lts_20211102::StrSplit<char const*>(absl::lts_20211102::strings_internal::ConvertibleToStringView, char const*) in decompressor_test.cpp.o
      absl::lts_20211102::strings_internal::Splitter<absl::lts_20211102::strings_internal::SelectDelimiter<char const*>::type, absl::lts_20211102::AllowEmpty, std::__1::basic_string_view<char, std::__1::char_traits<char> > > absl::lts_20211102::StrSplit<char const*>(absl::lts_20211102::strings_internal::ConvertibleToStringView, char const*) in libsilkworm_noded.a(path.cpp.o)
      absl::lts_20211102::strings_internal::Splitter<absl::lts_20211102::strings_internal::SelectDelimiter<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type, absl::lts_20211102::AllowEmpty, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > absl::lts_20211102::StrSplit<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, 0>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in libsilkworm_noded.a(directories.cpp.o)
  "google::protobuf::StringPiece::LogFatalSizeTooBig(unsigned long, char const*)", referenced from:
      google::protobuf::StringPiece::CheckedSsizeTFromSizeT(unsigned long) in libsilkworm_noded.a(types.pb.cc.o)
      google::protobuf::StringPiece::CheckedSsizeTFromSizeT(unsigned long) in libsilkworm_noded.a(ethbackend.pb.cc.o)
      google::protobuf::StringPiece::CheckedSsizeTFromSizeT(unsigned long) in libsilkworm_noded.a(kv.pb.cc.o)
  "google::protobuf::Empty::Empty(google::protobuf::Arena*)", referenced from:
      google::protobuf::Empty::Empty() in backend_kv_server_test.cpp.o
      google::protobuf::Empty::Empty() in libsilkworm_noded.a(ethbackend.grpc.pb.cc.o)
      google::protobuf::Empty::Empty() in libsilkworm_noded.a(kv.grpc.pb.cc.o)
      google::protobuf::Empty::Empty() in libsilkworm_noded.a(sentry.grpc.pb.cc.o)
      google::protobuf::Empty::Empty() in libsilkworm_noded.a(backend_calls.cpp.o)
      google::protobuf::Empty::Empty() in libsilkworm_noded.a(kv_calls.cpp.o)
      google::protobuf::Empty::Empty() in libsilkworm_noded.a(sentry_client.cpp.o)
      ...
     (maybe you meant: google::protobuf::Empty::Empty(google::protobuf::Arena*, bool))
  "google::protobuf::internal::VerifyUTF8(google::protobuf::StringPiece, char const*)", referenced from:
      google::protobuf::internal::VerifyUTF8(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*, char const*) in libsilkworm_noded.a(types.pb.cc.o)
      google::protobuf::internal::VerifyUTF8(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*, char const*) in libsilkworm_noded.a(ethbackend.pb.cc.o)
      google::protobuf::internal::VerifyUTF8(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*, char const*) in libsilkworm_noded.a(kv.pb.cc.o)
  "google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)", referenced from:
      google::protobuf::internal::InitSCC(google::protobuf::internal::SCCInfoBase*) in libsilkworm_noded.a(types.pb.cc.o)
      google::protobuf::internal::InitSCC(google::protobuf::internal::SCCInfoBase*) in libsilkworm_noded.a(ethbackend.pb.cc.o)
      google::protobuf::internal::InitSCC(google::protobuf::internal::SCCInfoBase*) in libsilkworm_noded.a(kv.pb.cc.o)
      google::protobuf::internal::InitSCC(google::protobuf::internal::SCCInfoBase*) in libsilkworm_noded.a(sentry.pb.cc.o)
  "google::protobuf::internal::ExtensionSet::RegisterExtension(google::protobuf::MessageLite const*, int, unsigned char, bool, bool)", referenced from:
      void google::protobuf::internal::PrimitiveTypeTraits<unsigned int>::Register<google::protobuf::FileOptions>(int, unsigned char, bool) in libsilkworm_noded.a(types.pb.cc.o)
     (maybe you meant: google::protobuf::internal::ExtensionSet::RegisterExtension(google::protobuf::MessageLite const*, int, unsigned char, bool, bool, char const* (*)(char const*, google::protobuf::internal::ParseContext*)))
  "google::protobuf::internal::AddDescriptors(google::protobuf::internal::DescriptorTable const*)", referenced from:
      ___cxx_global_var_init in libsilkworm_noded.a(types.pb.cc.o)
      ___cxx_global_var_init in libsilkworm_noded.a(ethbackend.pb.cc.o)
      ___cxx_global_var_init in libsilkworm_noded.a(kv.pb.cc.o)
      ___cxx_global_var_init in libsilkworm_noded.a(sentry.pb.cc.o)
  "google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, google::protobuf::Arena*)", referenced from:
      types::NodeInfoReply::set_id(char const*) in backend_kv_server_test.cpp.o
      types::NodeInfoReply::set_name(char const*) in backend_kv_server_test.cpp.o
      remote::Cursor::set_bucketname(char const*) in backend_kv_server_test.cpp.o
      remote::Cursor::set_k(char const*) in backend_kv_server_test.cpp.o
      remote::Cursor::set_v(char const*) in backend_kv_server_test.cpp.o
      remote::AccountChange::set_data(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) in libsilkworm_noded.a(state_change_collection.cpp.o)
      remote::AccountChange::set_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) in libsilkworm_noded.a(state_change_collection.cpp.o)
      ...
  "google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, google::protobuf::Arena*)", referenced from:
      types::ExecutionPayload::ExecutionPayload(types::ExecutionPayload const&) in libsilkworm_noded.a(types.pb.cc.o)
      types::ExecutionPayload::_internal_set_extradata(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libsilkworm_noded.a(types.pb.cc.o)
      types::NodeInfoReply::NodeInfoReply(types::NodeInfoReply const&) in libsilkworm_noded.a(types.pb.cc.o)
      types::NodeInfoReply::_internal_set_id(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libsilkworm_noded.a(types.pb.cc.o)
      types::NodeInfoReply::_internal_set_name(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libsilkworm_noded.a(types.pb.cc.o)
      types::NodeInfoReply::_internal_set_enode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libsilkworm_noded.a(types.pb.cc.o)
      types::NodeInfoReply::_internal_set_enr(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libsilkworm_noded.a(types.pb.cc.o)
      ...
  "google::protobuf::internal::ArenaStringPtr::Mutable(google::protobuf::internal::ArenaStringPtr::EmptyDefault, google::protobuf::Arena*)", referenced from:
      types::ExecutionPayload::_internal_mutable_extradata() in libsilkworm_noded.a(types.pb.cc.o)
      types::ExecutionPayload::InternalSwap(types::ExecutionPayload*) in libsilkworm_noded.a(types.pb.cc.o)
      types::NodeInfoReply::_internal_mutable_id() in libsilkworm_noded.a(types.pb.cc.o)
      types::NodeInfoReply::_internal_mutable_name() in libsilkworm_noded.a(types.pb.cc.o)
      types::NodeInfoReply::_internal_mutable_enode() in libsilkworm_noded.a(types.pb.cc.o)
      types::NodeInfoReply::_internal_mutable_enr() in libsilkworm_noded.a(types.pb.cc.o)
      types::NodeInfoReply::_internal_mutable_listeneraddr() in libsilkworm_noded.a(types.pb.cc.o)
      ...
  "google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned long, void (*)(void*))", referenced from:
      types::H128* google::protobuf::Arena::CreateMaybeMessage<types::H128>(google::protobuf::Arena*) in libsilkworm_noded.a(types.pb.cc.o)
      types::H160* google::protobuf::Arena::CreateMaybeMessage<types::H160>(google::protobuf::Arena*) in libsilkworm_noded.a(types.pb.cc.o)
      types::H256* google::protobuf::Arena::CreateMaybeMessage<types::H256>(google::protobuf::Arena*) in libsilkworm_noded.a(types.pb.cc.o)
      types::H512* google::protobuf::Arena::CreateMaybeMessage<types::H512>(google::protobuf::Arena*) in libsilkworm_noded.a(types.pb.cc.o)
      types::H1024* google::protobuf::Arena::CreateMaybeMessage<types::H1024>(google::protobuf::Arena*) in libsilkworm_noded.a(types.pb.cc.o)
      types::H2048* google::protobuf::Arena::CreateMaybeMessage<types::H2048>(google::protobuf::Arena*) in libsilkworm_noded.a(types.pb.cc.o)
      types::VersionReply* google::protobuf::Arena::CreateMaybeMessage<types::VersionReply>(google::protobuf::Arena*) in libsilkworm_noded.a(types.pb.cc.o)
      ...
  "absl::lts_20211102::ByString::Find(std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned long) const", referenced from:
      absl::lts_20211102::strings_internal::SplitIterator<absl::lts_20211102::strings_internal::Splitter<absl::lts_20211102::ByString, absl::lts_20211102::AllowEmpty, std::__1::basic_string_view<char, std::__1::char_traits<char> > > >::operator++() in decompressor_test.cpp.o
      absl::lts_20211102::strings_internal::SplitIterator<absl::lts_20211102::strings_internal::Splitter<absl::lts_20211102::ByString, absl::lts_20211102::AllowEmpty, std::__1::basic_string_view<char, std::__1::char_traits<char> > > >::operator++() in libsilkworm_noded.a(path.cpp.o)
      absl::lts_20211102::strings_internal::SplitIterator<absl::lts_20211102::strings_internal::Splitter<absl::lts_20211102::ByString, absl::lts_20211102::AllowEmpty, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::operator++() in libsilkworm_noded.a(directories.cpp.o)
  "google::protobuf::internal::ArenaImpl::SpaceAllocated() const", referenced from:
      google::protobuf::Arena::SpaceAllocated() const in libsilkworm_noded.a(types.pb.cc.o)
      google::protobuf::Arena::SpaceAllocated() const in libsilkworm_noded.a(ethbackend.pb.cc.o)
      google::protobuf::Arena::SpaceAllocated() const in libsilkworm_noded.a(kv.pb.cc.o)
      google::protobuf::Arena::SpaceAllocated() const in libsilkworm_noded.a(sentry.pb.cc.o)
```


3. Codewise suggestions:

    1. move profiles to under "cmake/profiles/*" - this is where all our build scripts reside.
    1. extract the DEPENDENCY_LIST to a separate file and include() it. Currently we have cmake/Hunter/config.cmake. Could be called cmake/packages.cmake .
    1. There's quite a bit of duplication in if/else branches. I wonder if this could be reduced. In particular often the difference is "CONFIG" for Hunter. But sometimes it is included without "CONFIG". What does it do? Could it work with either?

**Comment by battlmonstr** [comment]
@canepat why did you close this?

**Comment by canepat** [comment]
> @canepat why did you close this?

I didn't close it neither intentionally nor accidentally. Moreover, it is not possible to reopen it anymore.

Maybe is this related with: 1) you rebased it onto `boost` branch 2) we have automatic deletion of branch after merge on `master` 3) this PR comes from a fork?

:thinking:

**Comment by battlmonstr** [comment]
@canepat I see. Interesting, so the other PRs that were based on "boost" were automatically rebased to master after you've merged it, but not this one. I've revived it as https://github.com/torquem-ch/silkworm/pull/863 , because it is not possible to reopen.

**Pull request closed without merging**
