### PR TITLE
Welcome to 2021!!!

### PR DESCRIPTION
**Pull request by gcolvin**
Previous merge of this branch left date changes behind.

### CODE REVIEW

**Review by gcolvin — COMMENTED** [review]
It's 2021.

**Comment by yperbasis** [comment]
As far as I understand it, the copyright year should be the year of the first edition: [Copyright Notice Wiki](https://en.wikipedia.org/wiki/Copyright_notice#Form_of_notice_for_visually_perceptible_copies). I.e. we should leave it as 2020. Perhaps we can also add 2021, but 2020 should stay there. See also https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

I suggest that we simply have one copyright year per file, namely the year the file was created, and not bother updating it.

**Review by yperbasis — CHANGES_REQUESTED** [review]
As far as I understand it, the copyright year should be the year of the first edition: [Copyright Notice Wiki](https://en.wikipedia.org/wiki/Copyright_notice#Form_of_notice_for_visually_perceptible_copies). I.e. we should leave it as 2020. Perhaps we can also add 2021, but 2020 should stay there. See also https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

I suggest that we simply have one copyright year per file, namely the year the file was created, and not bother updating it.

**Comment by AndreaLanfranchi** [comment]
@yperbasis I believe having first (eventually only) year as the date of creation while adding as second year the one file was last modified makes no harm and gives an immediate perception of "stale" vs "active" files.
So having 2020 - 2021 should be ok ... imho

**Comment by yperbasis** [comment]
Yeah, I guess 2020-2021 or 2020, 2021 is fine.

**Review by AndreaLanfranchi — APPROVED** [review]

**Review by yperbasis — APPROVED** [review]

**Pull request merged**
