### PR TITLE
added unwinds and test for blockhashes stage

### PR DESCRIPTION
**Pull request by Giulio2002**

### CODE REVIEW

**Comment by yperbasis** [comment]
Hmm, I wonder why the Appveyor build is failing. Do you have a Windows machine handy? Can you try debugging there?

**Comment by AndreaLanfranchi** [comment]
> Hmm, I wonder why the Appveyor build is failing. Do you have a Windows machine handy? Can you try debugging there?

The issue is here <https://github.com/torquem-ch/silkworm/pull/340/files#diff-a1f3ecd914164748b2e2398c7a5ee401fdc458b51a430451fc385add7be6853eR68>

The collector path passed to `stagedsync::stage_blockhashes` is the very [root of data_dir](https://github.com/torquem-ch/silkworm/pull/340/files#diff-a1f3ecd914164748b2e2398c7a5ee401fdc458b51a430451fc385add7be6853eR46).
In `stagedsync::stage_blockhashes` the collector is instantiated and destroyed and his destructor tries to delete the working dir which cannot be deleted cause the db is still open in higher scope.

Two changes needed 
1) pass the stage the path returned by data_dir.get_etl_path()
2) remove the deletion of `work_path_` from collector destructor otherwise we keep deleting the etl_dir

Very strange does not happen on Linux

**Review by yperbasis — APPROVED** [review]

**Review by AndreaLanfranchi — APPROVED** [review]
LGTM.
@yperbasis  ?

**Comment by yperbasis** [comment]
> LGTM.
> @yperbasis ?

Yes, looks good to me as well.

**Pull request merged**
