### PR TITLE
Use of transaction manager in unwind_execution test

### PR DESCRIPTION
**Pull request by Giulio2002**

### CODE REVIEW

**Comment by Giulio2002** [comment]
now it's more standard

**Review by yperbasis — COMMENTED** [review]
Well, this variant works, but the previous one was also fine. In the previous variant `TransactionManager` was created in the external transaction mode, implying that `stagedsync::unwind_execution()` doesn't actually commit the transaction. In the new variant `stagedsync::unwind_execution()` does commit and then `TransactionManager` renews the transaction. Both variants are valid, so not sure what we achieve with this change.

**Comment by Giulio2002** [comment]
@yperbasis In my opinion, it is more clear now, before we needed to make a transaction manager to be passed to unwind_execution in the middle of the code and not at the beggining, thus i think now it's more standard compared to the others unwind tests

**Review by yperbasis — APPROVED** [review]
OK, fine, I'm happy with the new variant as well.

**Pull request merged**
