### PR TITLE
Split libsilkworm into silkworm_core & silkworm_db

### PR DESCRIPTION
**Pull request by yperbasis**
Essential Ethereum protocol logic will live in core (block execution, RLP, root hash algorithms, etc), while silkworm_db will contain LMDB access logic and TG-specific things. The reason is two-fold. First, a smaller core library will make Silkworm easier to use for things like eth_call, where TG & LMDB paraphernalia is not required. Second, the smaller core can potentially be compiled into WebAssembly, which is a strategic goal for us (in particular for the Internet Computer project by Dfinity).

### CODE REVIEW

**Review by canepat — APPROVED** [review]
Looks good to me

**Review by AndreaLanfranchi — COMMENTED** [review]
Is a large change.
OOF now ...please let me check a full compile on Windows tomorrow morning

**Comment by yperbasis** [comment]
> Is a large change.
> OOF now ...please let me check a full compile on Windows tomorrow morning

@AndreaLanfranchi  Sure, thank you!

**Comment by AndreaLanfranchi** [comment]
@yperbasis looks good to me too.
I took the liberty to amend a couple of narrow casting warnings.

I still get a lot of warnings though mainly due to CXX17 deprecations on subprojects: abseil cbor and mdb.c mainly

**Pull request merged**
