### PR TITLE
First byte histogram

### PR DESCRIPTION
**Pull request by yperbasis**
A utility to calculate the number of smart contracts whose first byte is 0xEF. See [EIP-3541](https://eips.ethereum.org/EIPS/eip-3541).

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
Nice ... can we take it on hold till we merge `integration` branch so we can integrate into toolbox instead of having stand alone executable ?

**Comment by yperbasis** [comment]
> Nice ... can we take it on hold till we merge `integration` branch so we can integrate into toolbox instead of having stand alone executable ?

Sure, it's not urgent.

**Comment by AndreaLanfranchi** [comment]
Mind if we close this ?
Implemented [here](https://github.com/torquem-ch/silkworm/commit/7cd2dcfde4aab0e63da8b22145e4e6ace3e04e4a)

**Comment by yperbasis** [comment]
Right, let's close this one.

**Pull request closed without merging**
