### PR TITLE
Restore stage uniformity

### PR DESCRIPTION
**Pull request by yperbasis**
Stage uniformity is useful for future work (something similar to `erigon/eth/stagedsync/default_stages.go`).

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
In my personal opinion there's more work to do on this matter.
I understand having the same signature for common methods is useful but I don't think is acceptable to have only `EnvConfig` as parameter. We should normalize stages passing **all** useful informations and making them suitable to fit in a stage loop (with a common transaction.

**Comment by AndreaLanfranchi** [comment]
Also we should agree on common methods naming: eg `forward` and [`unwind`|`rewind`]

**Comment by yperbasis** [comment]
> In my personal opinion there's more work to do on this matter.
> I understand having the same signature for common methods is useful but I don't think is acceptable to have only `EnvConfig` as parameter. We should normalize stages passing **all** useful informations and making them suitable to fit in a stage loop (with a common transaction.

Yes, absolutely, more work and more parameters will be required. For instance, I'm going to add `external_txn` (useful we we only have a handful of blocks and want to do several stages inside a single transaction). This PR is just a stepping stone.

**Review by AndreaLanfranchi — APPROVED** [review]
I approve with reserve: not happy to loose command line arguments specifically the one which could set the batchsize

**Pull request merged**
