### PR TITLE
small speedup in from_hex

### PR DESCRIPTION
**Pull request by greg7mdp**
I checked it, this version is about 9% faster (tried with G++ -O3). Since the code is also simpler I think it is a good change.

If performance for this function is important, I have another change that makes it about 7% faster yet by unrolling the loop, but the code is a little more complicated. Let me know if you are interested!

Here is a test program:

```
#include <cassert>
#include <regex>

#include <optional>

#include <cstddef>
#include <cstdint>
#include <string>
#include <string_view>

using Bytes = std::basic_string<uint8_t>;

template<typename time_unit = std::milli>
class Timer
{
public:
    Timer()                 { reset(); }
    void reset()            { _start = _snap = clock::now();  }
    void snap()             { _snap = clock::now();  }

    float get_total() const { return get_diff<float>(_start, clock::now()); }
    float get_delta() const { return get_diff<float>(_snap, clock::now());  }

private:
    using clock = std::chrono::high_resolution_clock;
    using point = std::chrono::time_point<clock>;

    template<typename T>
    static T get_diff(const point& start, const point& end)
    {
        using duration_t = std::chrono::duration<T, time_unit>;

        return std::chrono::duration_cast<duration_t>(end - start).count();
    }

    point _start;
    point _snap;
};


// ASCII -> hex value (0xbc means bad [hex] char)
static constexpr uint8_t kUnhexTable[256] = {
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
    0x09, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc};

// ASCII -> hex value << 4 (upper nibble) (0xbc means bad [hex] char)
static constexpr uint8_t kUnhexTable4[256] = {
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0x00, 0x10, 0x20, 0x30, 0x40, 0x50, 0x60, 0x70, 0x80,
    0x90, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xa0, 0xb0, 0xc0, 0xd0, 0xe0, 0xf0, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xa0, 0xb0, 0xc0, 0xd0, 0xe0, 0xf0, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc,
    0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc, 0xbc};

static inline uint8_t unhex_lut(uint8_t x) { return kUnhexTable[x]; }
static inline uint8_t unhex_lut4(uint8_t x) { return kUnhexTable4[x]; }

static std::string tst_str =
    "f9021af90215a0abec7af08dfaf663ff46e645eab70a168e82a03a227cbcaccba9e455d1e42522a01dcc4de8de"
    "c75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d493479452bc44d5378309ee2abf1539bf71de1b7d"
    "7be3b5a0bc4da42c51a54602e97563f49e236495284a4efdd4514d2de45f25b6f1ffd5a8a056e81f171bcc55a6"
    "ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b"
    "996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000"
    "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "008606163d60348e83035a50832fefd8808455f332b898d783010103844765746887676f312e342e32856c696e"
    "7578a00ae8d616f3aad20be71ec927e731b4202f24ed0e88f8a35422fb6d15fa5c2d1088f54d19221bacb6b4c0"
    "c0";

std::optional<Bytes> from_hex(std::string_view hex) noexcept {
    if (hex.length() >= 2 && hex[0] == '0' && (hex[1] == 'x' || hex[1] == 'X')) {
        hex.remove_prefix(2);
    }
    if (hex.empty()) {
        return Bytes{};
    }

    size_t pos(hex.length() & 1);  // "[0x]1" is legit and has to be treated as "[0x]01"
    Bytes out((hex.length() + pos) / 2, '\0');
    const char* src{const_cast<char*>(hex.data())};
    const char* last = src + hex.length();
    uint8_t* dst{&out[0]};

    if (pos) {
        auto b{unhex_lut(static_cast<uint8_t>(*src++))};
        if (b == 0xbc) {
            return std::nullopt;
        }
        *dst++ = b;
    }

#if 0
    for (; pos < out.length(); ++pos) {
#else
    while (src < last) {
#endif
        auto a{unhex_lut4(static_cast<uint8_t>(*src++))};
        auto b{unhex_lut(static_cast<uint8_t>(*src++))};
        if (a == 0xbc || b == 0xbc) {
            return std::nullopt;
        }
        *dst++ = a | b;
    }
    return out;
}

int main()
{
    Timer<std::milli> timer;
    printf("times: ");
    size_t res;
    float sum_times{0};
    const int num_iter = 5;
    for (int iter=0; iter < num_iter; ++iter)
    {
        res = 0;
        timer.snap();

        for (size_t i=0; i<10000000; ++i)
            res += (*from_hex(tst_str))[0];

        printf("%5.2f ", timer.get_delta() / 1000);
        sum_times += timer.get_delta() / 1000;
    }
    printf(" - average %5.2f (res = %ld)\n", sum_times / num_iter, res);
    return 0;
}
```

### CODE REVIEW

**Review by yperbasis — APPROVED** [review]

**Comment by AndreaLanfranchi** [comment]
While I'm certainly interested in seeing the version with "unrolled loop" I have a concern about the validity of the test.
Particularly this
```
        for (size_t i=0; i<10000000; ++i)
            res += (*from_hex(tst_str))[0];
```
as `tst_str` is constant the processor can easily branch predict the addendum to res for each iteration.
Have you tried with a large enough array of randomly populated hex strings ?

**Comment by yperbasis** [comment]
Currently `from_hex` is used primarily in tests, so it's not performance critical. This change is fine because is doesn't complicate the code, but otherwise I wouldn't spend too much brain cycles on this method.

**Comment by greg7mdp** [comment]
> While I'm certainly interested in seeing the version with "unrolled loop"

Just for info, here is the code with the unrolled loop (addition between #if). I also changed the `bad value` in the lut from `0xbc` to `0xff`.

```
std::optional<Bytes> from_hex(std::string_view hex) noexcept {
    if (hex.length() >= 2 && hex[0] == '0' && (hex[1] == 'x' || hex[1] == 'X')) {
        hex.remove_prefix(2);
    }
    if (hex.empty()) {
        return Bytes{};
    }

    size_t pos(hex.length() & 1);  // "[0x]1" is legit and has to be treated as "[0x]01"
    Bytes out((hex.length() + pos) / 2, '\0');
    const char* src{const_cast<char*>(hex.data())};
    const char* last = src + hex.length();
    uint8_t* dst{&out[0]};

    if (pos) {
        auto b{unhex_lut(static_cast<uint8_t>(*src++))};
        if (b == 0xff) {
            return std::nullopt;
        }
        *dst++ = b;
    }

#if 1
    // 5-10% faster
    while (last - src >= 8) {
        auto a{unhex_lut4(static_cast<uint8_t>(*src++))};
        auto b{unhex_lut(static_cast<uint8_t>(*src++))};
        auto c{unhex_lut4(static_cast<uint8_t>(*src++))};
        auto d{unhex_lut(static_cast<uint8_t>(*src++))};
        auto e{unhex_lut4(static_cast<uint8_t>(*src++))};
        auto f{unhex_lut(static_cast<uint8_t>(*src++))};
        auto g{unhex_lut4(static_cast<uint8_t>(*src++))};
        auto h{unhex_lut(static_cast<uint8_t>(*src++))};
        if ((b | d | f | h) == 0xFF || (a | c | e | g) == 0xFF ) {
            return std::nullopt;
        }
        *dst++ = a | b;
        *dst++ = c | d;
        *dst++ = e | f;
        *dst++ = g | h;
    }
#endif
    while (src < last) {
        auto a{unhex_lut4(static_cast<uint8_t>(*src++))};
        auto b{unhex_lut(static_cast<uint8_t>(*src++))};
        if (a == 0xff || b == 0xff) {
            return std::nullopt;
        }
        *dst++ = a | b;
    }
    return out;
}
```

> as tst_str is constant the processor can easily branch predict the addendum to res for each iteration.

Hum, that would not be branch prediction right, you mean optimize the loop away? I don't think it happens.

> Have you tried with a large enough array of randomly populated hex strings ?

No I haven't.

**Comment by AndreaLanfranchi** [comment]
@greg7mdp definitely good.
Should you have time to push a PR I'd definitely merge it.
As @yperbasis to_hex is not actually critical for the project but nevertheless we can have best code in our repo to validate overall quality. Thanks

**Pull request merged**
