### PR TITLE
mdbx::slice::data() instead of iov_base

### PR DESCRIPTION
**Pull request by yperbasis**
`iov_base` looks like an implementation detail we shouldn't rely upon

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
Why this ?
I understand the removal of `byte_ptr` but why remove `iov_base/iov_len` if both `data()` and `length()` return the very same values ?

**Comment by yperbasis** [comment]
Semantically `mdbx::slice` is very close to `std::string_view`. `std::string_view`,  `std::string`, and `std::vector` all have the `data()` member function, while `iov_base` looks more niche, and `MDBX_val` being `iovec` seems like an implementation detail to me.

**Comment by AndreaLanfranchi** [comment]
Well ... the difference is `mdbx::slice::data()` returns a `void*` to data (by iovec) while the others you mentioned return a `T*` to data where T is the undelying type. Not much difference as long as we static cast always to bytes but `iovec` is more "generic" and depicts a raw memory ptr.

**Comment by yperbasis** [comment]
It's about names and the API. In the C++ world `data()` is more commonly used and widely understood than `iov_base` (at least that's my impression). When a new reader sees `data()` in our code, he is more likely to get the meaning compared to him seeing `iov_base`.

**Comment by AndreaLanfranchi** [comment]
Ok for me then.

**Review by AndreaLanfranchi — APPROVED** [review]

**Comment by greg7mdp** [comment]
I like this change as well. `iov_base` looks like accessing an internal variable, while `data()` resembles a proper api.

**Pull request merged**
