### PR TITLE
First cut of cmd/trie

### PR DESCRIPTION
**Pull request by yperbasis**
Part of Issue #179

### CODE REVIEW

**Review by AskAlexSharov — APPROVED** [review]
```
 if (!storage_trie.key()) {
                        break;
```
Is it right way to check end of bucket in Silkworm? Not check for "ErrNotFound"?

**Comment by AndreaLanfranchi** [comment]
> ```
>  if (!storage_trie.key()) {
>                         break;
> ```
> 
> Is it right way to check end of bucket in Silkworm? Not check for "ErrNotFound"?

Yes. This is due to cursor implementation where the seek method returns a std::null_opt on not found error.

**Review by AndreaLanfranchi — APPROVED** [review]
I've added a commit for clarity on optionals.
Besides I still see a lot of TODOs on cursors operations.
Dunno if its worth change this to a WIP PR.
But for me code so far is good.

**Comment by yperbasis** [comment]
> I've added a commit for clarity on optionals.
> Besides I still see a lot of TODOs on cursors operations.
> Dunno if its worth change this to a WIP PR.
> But for me code so far is good.

I'm still working on Stage 7: Compute State Root Stage (IntermediateHashes), so there's still a lot of TODOs. However, I'd like to submit smaller PRs if possible, provided they don't break other stuff. I find smaller PRs easier to review, while one can easily get lost with in a gigantic PR :)

**Pull request merged**
