### PR TITLE
Refactor commands CMakeLists

### PR DESCRIPTION
**Pull request by battlmonstr**
* sort commands alphabetically
* codify a convention that each cmd has a corresponding main cpp file with the same name
* CLI11 and silkworm_node libraries (COMMON_LIBS) are required for each cmd
* adding custom libs or sources is still possible with LIBS/SRC

Note: silkworm_libs variable is introduced as a replacement for `$<$<BOOL:${MSVC}>`, which didn't expand when passed as a parameter.

Note: a similar goal refactoring was done in [erigon's Makefile](https://github.com/ledgerwatch/erigon/blob/devel/Makefile#L68) for look-alike commands to avoid code duplication and discrepancies.

### CODE REVIEW

**Comment by canepat** [comment]
I appreciate the intent of this PR, nevertheless I agree with @AndreaLanfranchi about losing WYSIWYG. In particular, IMHO the `NO_NODE_LIB` argument of the `cmd` function is a bit obscure at first glance.

I haven't a strong opinion about this PR. I'm not against it, but I would require to remove the `NO_NODE_LIB` argument and explicitly list all the libraries where `cmd` is called, so that both sources and libraries are visible at the call site.

**Comment by battlmonstr** [comment]
@canepat Removed NO_NODE_LIB. The silkworm_node library is mandatory for all the commands now. It doesn't make much sense to special case genesistool as it obscures it for the rest.
I have also extracted the COMMON_LIBS variable so that it is explicit now. Since CLI11 and silkworm_node are common, does it make sense to list them for each command?

@AndreaLanfranchi yes, functions do hide real code. In terms of readability `cmd(bla)` is as explicit as it can be. I have added some docs for you ❤️ so that it is not as scary/unfamiliar.

**Comment by AndreaLanfranchi** [comment]
> @canepat Removed NO_NODE_LIB. The silkworm_node library is mandatory for all the commands now. It doesn't make much sense to special case genesistool as it obscures it for the rest. I have also extracted the COMMON_LIBS variable so that it is explicit now. Since CLI11 and silkworm_node are common, does it make sense to list them for each command?
> 
> @AndreaLanfranchi yes, functions do hide real code. In terms of readability `cmd(bla)` is as explicit as it can be. I have added some docs for you ❤️ so that it is not as scary/unfamiliar.

Did I make something to you ? I really wish not to be trated as an idiot ok ?
To be precise this is not a function rather a MACRO which rewrites the cmake build files.
For the very same reasons we do NOT want to use MACROs in C++ code as well.

**Comment by battlmonstr** [comment]
@AndreaLanfranchi just to be clear, I was sincere, no sarcasm. If I offended you, I apologize.

**Comment by mriccobene** [comment]
I would prefer the current version of cmd/CMakeLists.txt to be unmodified as it is easier to read and modify. Also I am concerned that Clion may not automatically recognize targets.

**Pull request closed without merging**
