### PR TITLE
Bump benchmark 1.6.1

### PR DESCRIPTION
**Pull request by AndreaLanfranchi**

### CODE REVIEW

**Comment by canepat** [comment]
Build failed in AppVeyor with message `Build exceeded allowed resource quotas`. I am wondering if this is strictly related to this version bump.

**Comment by yperbasis** [comment]
I've purged AppVeyor Hunter cache and restarted the build. Let's see what happens.

**Review by yperbasis — APPROVED** [review]

**Comment by canepat** [comment]
> I've purged AppVeyor Hunter cache and restarted the build. Let's see what happens.

Thanks. How do you purge AppVeyor Hunter cache? Is it an administrative operation from the Silkworm account in AppVeyor?

**Comment by yperbasis** [comment]
> > I've purged AppVeyor Hunter cache and restarted the build. Let's see what happens.
> 
> Thanks. How do you purge AppVeyor Hunter cache? Is it an administrative operation from the Silkworm account in AppVeyor?

I send the following [REST API](https://www.appveyor.com/docs/build-cache/#rest-api) request:
```
DELETE https://ci.appveyor.com/api/projects/torquem/silkworm/buildcache
```
(with an authorization Header of course)

**Pull request merged**
