### PR TITLE
issue #195 - speedup etl by avoiding unnecessary copies

### PR DESCRIPTION
**Pull request by greg7mdp**
I haven't tested it besides running core_test and node_test, but it is simple enough that it should work and avoid unnecessary etl::Entry copies.
Each etl::Entry copy will cause two `malloc()` when allocating the new std::basic_string, two data copies,  and two `free()` when the original is destructed. Doing a move avoids all this.

### CODE REVIEW

**Comment by Giulio2002** [comment]
Master has following performance: 

``` Done in 29.354s

 [Buffer-Default] First loop ...
 [Buffer-Default copy build] Done in 898.685ms
 [Buffer-Default] Second loop ...
 [Buffer-Default copy build] Done in 606.608ms


 [Buffer-Default] First loop ...
 [Buffer-Default move build] Done in 66.327ms
 [Buffer-Default] Second loop ...
 [Buffer-Default move build] Done in 32.103ms

```

Now we achieve:

```
 Feeding buffer base ...
 Done in 29.137s

 [Buffer-Default] First loop ...
 [Buffer-Default copy build] Done in 865.616ms
 [Buffer-Default] Second loop ...
 [Buffer-Default copy build] Done in 716.927ms


 [Buffer-Default] First loop ...
 [Buffer-Default move build] Done in 68.371ms
 [Buffer-Default] Second loop ...
 [Buffer-Default move build] Done in 25.281ms
```

**Review by Giulio2002 — APPROVED** [review]

**Comment by Giulio2002** [comment]
LGTM @AndreaLanfranchi, @yperbasis, anything to say here?

**Comment by greg7mdp** [comment]
@Giulio2002 that test you ran (bench_buffer.cpp) does not measure the change from the PR. It tests only the buffer itself, not inserting rvalue entries into a collector.

**Comment by AndreaLanfranchi** [comment]
Good for me too. Would be super-nice if you could also conver in collector_test.cpp the lines highlighted for codecoverage

**Comment by greg7mdp** [comment]
I think this last change should do it @AndreaLanfranchi

**Review by AndreaLanfranchi — APPROVED** [review]
Nice ! Ty @greg7mdp

**Pull request merged**
