### PR TITLE
Update lgtm.yml

### PR DESCRIPTION
**Pull request by AndreaLanfranchi**
# DO NOT MERGE YET PLEASE

### CODE REVIEW

**Comment by yperbasis** [comment]
@AndreaLanfranchi can you try `make -j` instead of `make . -j`?

**Comment by AndreaLanfranchi** [comment]
> @AndreaLanfranchi can you try `make -j` instead of `make . -j`?

Done but it can't complete. Last attempt is timed-out
https://lgtm.com/logs/0e32be625fa6080bf2365f557373430166ac4f5f/lang:cpp

**Comment by yperbasis** [comment]
IMHO lgtm.com is probably not a huge priority for us (we've already fixed highlighted issues in our code base). I'd put it on hold if it's taking too long to sort out.

**Comment by AndreaLanfranchi** [comment]
Will eventually catch up the issue in the future. Low priority now

**Pull request closed without merging**
