### PR TITLE
Lookups

### PR DESCRIPTION
**Pull request by AndreaLanfranchi**
Quick single record data retrieve and upsert

### CODE REVIEW

**Comment by yperbasis** [comment]
There are already convenience methods get and put in db::Table that handle ByteViews and check errors. For example, already_executed_block can be written as
```
    auto progress_table{txn->open(db::table::kSyncStageProgress)};
    ByteView stage_key{byte_view_of_c_str(KExecutionStage_key)};
    std::optional<ByteView> data{progress_table->get(stage_key)};
    if (data) {
        return boost::endian::load_big_u64(data->data());
    } else {
        return 0;
    }
```

**Comment by AndreaLanfranchi** [comment]
You missed the point of a generic method.
Maybe a discussion before closing abruptly ?

**Comment by yperbasis** [comment]
OK, so what's the point?

**Comment by AndreaLanfranchi** [comment]
Nevermind ... I see my support (if any) not well perceived.
You can remove my rights from this repo in any moment.

**Pull request closed without merging**
